include:
    - docker/docker-mysql.yml

services:
    sqlscript:
        image: jekkos/opensourcepos:sql-master
        command: /bin/sh -c 'exit 0'
    ospos:
        image: jekkos/opensourcepos:master
        restart: always
        depends_on:
            - mysql
        ports:
            - "80:80"
        networks:
            - app_net
        volumes:
            - ./app/Controllers/Items.php:/app/app/Controllers/Items.php
            - ./app/Views/items/manage.php:/app/app/Views/items/manage.php
            - ./app/Models/Stock_location.php:/app/app/Models/Stock_location.php
            - ./app/Helpers/tabular_helper.php:/app/app/Helpers/tabular_helper.php
            - ./app/Database/Migrations/20251225000000_add_items_view_permission.php:/app/app/Database/Migrations/20251225000000_add_items_view_permission.php
            - ./app/Database/tables.sql:/app/app/Database/tables.sql
            - uploads:/app/public/uploads
            - logs:/app/writable/logs
        environment:
            - CI_ENVIRONMENT=production
            - FORCE_HTTPS=false
            - PHP_TIMEZONE=UTC
            - MYSQL_USERNAME=admin
            - MYSQL_PASSWORD=pointofsale
            - MYSQL_DB_NAME=ospos
            - MYSQL_HOST_NAME=mysql
